import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: '.',
  testMatch: ['tests/e2e/**/*.spec.ts', 'tests/e2e/**/*.spec.js'],
  timeout: 30_000,
  retries: 0,
  workers: 1,
  reporter: 'list',
  use: {
    baseURL: 'http://localhost:5173',
    trace: 'on-first-retry',
    video: 'off',
    headless: true,
    launchOptions: {
      executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome',
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
    },
  },
  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
    {
      name: 'mobile-chrome',
      use: { ...devices['Desktop Chrome'], viewport: { width: 390, height: 844 }, hasTouch: true },
      testMatch: [
        'tests/e2e/ability-stack-bugs.spec.ts',
        'tests/e2e/ai-creature-evaluation-smoke.spec.ts',
        'tests/e2e/ancestral-recall-targeting.spec.ts',
        'tests/e2e/ante-system-complete.spec.ts',
        'tests/e2e/batch1a-desert-landwalk.spec.ts',
        'tests/e2e/batch1b-wall-destruction-sacrifice.spec.ts',
        'tests/e2e/batch-complex-tier-general.spec.ts',
        'tests/e2e/batch-moderate-tier-forge-2.spec.ts',
        'tests/e2e/batch-simple-tier-forge-1.spec.ts',
        'tests/e2e/card-type-line.spec.ts',
        'tests/e2e/copy-and-modal-choice.spec.ts',
        'tests/e2e/damage-shields.spec.ts',
        'tests/e2e/deferral-sweep-1.spec.ts',
        'tests/e2e/deferral-sweep-2-typechange.spec.ts',
        'tests/e2e/duel-controller.spec.ts',
        'tests/e2e/duel-persistence.spec.ts',
        'tests/e2e/dungeon-tileset.spec.ts',
        'tests/e2e/end-turn-with-activated-permanent.spec.ts',
        'tests/e2e/exile-zone.spec.ts',
        'tests/e2e/first-strike-combat.spec.ts',
        'tests/e2e/force-of-nature-mobile-parity.spec.ts',
        'tests/e2e/generalized-choice-mechanisms.spec.ts',
        'tests/e2e/henchman-visibility.spec.ts',
        'tests/e2e/hooded-figure-sprites.spec.ts',
        'tests/e2e/lotus-cancel-undo.spec.js',
        'tests/e2e/mobile-targeting.spec.ts',
        'tests/e2e/overworld-map-centering.spec.ts',
        'tests/e2e/overworld-mobile.spec.ts',
        'tests/e2e/overworld-sprites.spec.ts',
        'tests/e2e/overworld-tileset.spec.ts',
        'tests/e2e/overworld-visual.spec.ts',
        'tests/e2e/plaque-visibility.spec.ts',
        'tests/e2e/power-sink-x-select.spec.js',
        'tests/e2e/preduel-sandbox.spec.ts',
        'tests/e2e/ruins.spec.js',
        'tests/e2e/sandbox.spec.ts',
        'tests/e2e/structure-icons.spec.ts',
        'tests/e2e/tokens-and-poison.spec.ts',
        'tests/e2e/tutor-modal.spec.ts',
        'tests/e2e/undo-mana-taps-all-phases.spec.js',
      ],
    },
  ],
  webServer: {
    command: 'npm run dev',
    url: 'http://localhost:5173',
    reuseExistingServer: !process.env.CI,
    timeout: 60_000,
  },
});
